Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/LineLength:
  Max: 170

Metrics/BlockLength:
  Max: 70

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20
